# Generated by Django 2.2.1 on 2019-06-10 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_trade_finished',
        ),
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
    ]
